services:
  - type: web
    name: tripdeal-ia
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0